version: '3.8'
services:
  nestjs_app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres_db
    ports:
      - ${NEST_PORT}:${NEST_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEST_PORT=${NEST_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - API_URL=${API_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_ADDRESS=${RESEND_FROM_ADDRESS}
    volumes:
      - ./src:/usr/src/app/src

  postgres_db:
    container_name: postgres_db
    image: postgres:13
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  src:
  postgres:
    name: postgres_db
